name = "screenshots"
name_pretty = "Screenshots"
fixed_order = true
icon = ""

[[entries]]
text = "Fullscreen (instant)"
icon = ""
actions = { "fullscreen_instant" = "grimblast --notify copysave screen ~/Downloads/$(date +%Y%m%d-%H%M%S).png" }

[[entries]]
text = "Fullscreen (2s delay)"
icon = ""
actions = { "fullscreen_delay" = "sleep 2 && grimblast --notify copysave screen ~/Downloads/$(date +%Y%m%d-%H%M%S).png" }

[[entries]]
text = "Select Area (instant)"
icon = ""
actions = { "area_instant" = "grimblast --freeze --notify copysave area ~/Downloads/$(date +%Y%m%d-%H%M%S).png" }

[[entries]]
text = "Select Area (2s delay)"
icon = ""
actions = { "area_delay" = "sleep 2 && grimblast --freeze --notify copysave area ~/Downloads/$(date +%Y%m%d-%H%M%S).png" }
